version: "3"
services:
  redos:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "1234:1234"
    restart: always
    environment:
      - REDOS_FLAG=flag{b4rr3l_thumb5_hum4n1ty}
      - REGEX_ID=0
      - MAXCHARS=2020
