version: "3"
services:
  ssrf:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "7888:8888"
    restart: always
    environment:
      - SSRF_FLAG=flag{knight_admires_situation}

